name: Docker build & push

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USER }}/flask-app:latest .

      - name: Push Docker image
        run: docker push ${{ vars.DOCKERHUB_USER }}/flask-app:latest