name: hello

on:
  workflow_dispatch:

    paths:
      - '**.html'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello Prateek
        run: echo "Hello Prateek"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show Docker version
        run: docker --version
