name: hello

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - '**.html'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Prateek"

  details:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version